# Generated by Django 6.0.3 on 2026-03-16 12:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(help_text='Jenkins job name', max_length=200, verbose_name='Job ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('job_type', models.CharField(choices=[('freestyle', 'Freestyle'), ('pipeline', 'Pipeline'), ('multibranch', 'Multi-branch Pipeline'), ('folder', 'Folder'), ('workflow', 'Workflow')], default='pipeline', max_length=50, verbose_name='Type')),
                ('url', models.URLField(blank=True, verbose_name='Job URL')),
                ('config_xml', models.TextField(blank=True, help_text='Job configuration', verbose_name='Config XML')),
                ('parameters', models.JSONField(blank=True, default=list, help_text='Build parameters', verbose_name='Parameters')),
                ('color', models.CharField(blank=True, help_text='Jenkins job color', max_length=50, verbose_name='Color')),
                ('health_report', models.JSONField(blank=True, default=dict, verbose_name='Health Report')),
                ('last_build_number', models.IntegerField(default=0, verbose_name='Last Build Number')),
                ('last_build_status', models.CharField(blank=True, max_length=50, verbose_name='Last Build Status')),
                ('last_build_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Build At')),
                ('build_count', models.IntegerField(default=0, verbose_name='Build Count')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synced At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'db_table': 'jenkins_jobs',
                'ordering': ['server', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JenkinsPipeline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parameters')),
                ('environment', models.JSONField(blank=True, default=dict, verbose_name='Environment')),
                ('pipeline_script', models.TextField(blank=True, help_text='Jenkinsfile content', verbose_name='Pipeline Script')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jenkins_pipelines', to=settings.AUTH_USER_MODEL)),
                ('jobs', models.ManyToManyField(blank=True, related_name='pipelines', to='jenkins_app.jenkinsjob')),
            ],
            options={
                'db_table': 'jenkins_pipelines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JenkinsServer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(help_text='e.g., http://jenkins:8080', verbose_name='Jenkins URL')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=500, verbose_name='Password')),
                ('timeout', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)], verbose_name='Timeout (seconds)')),
                ('max_concurrent_builds', models.IntegerField(default=10, verbose_name='Max Concurrent Builds')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20, verbose_name='Status')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Jenkins Version')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jenkins_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jenkins_servers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JenkinsPlugin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plugin_id', models.CharField(max_length=200, verbose_name='Plugin ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('version', models.CharField(max_length=50, verbose_name='Version')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, verbose_name='Plugin URL')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('has_update', models.BooleanField(default=False, verbose_name='Has Update')),
                ('compatible_version', models.CharField(blank=True, max_length=50, verbose_name='Compatible Version')),
                ('dependencies', models.JSONField(blank=True, default=list, verbose_name='Dependencies')),
                ('installed_at', models.DateTimeField(blank=True, null=True, verbose_name='Installed At')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated At')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='jenkins_app.jenkinsserver')),
            ],
            options={
                'db_table': 'jenkins_plugins',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JenkinsNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=200, verbose_name='Node ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('node_type', models.CharField(choices=[('master', 'Master'), ('agent', 'Agent'), ('cloud', 'Cloud')], default='agent', max_length=20, verbose_name='Type')),
                ('url', models.URLField(blank=True, verbose_name='Node URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('disconnected', 'Disconnected')], default='offline', max_length=20, verbose_name='Status')),
                ('offline_reason', models.TextField(blank=True, verbose_name='Offline Reason')),
                ('num_executors', models.IntegerField(default=2, verbose_name='Number of Executors')),
                ('total_memory', models.FloatField(blank=True, null=True, verbose_name='Total Memory (GB)')),
                ('free_memory', models.FloatField(blank=True, null=True, verbose_name='Free Memory (GB)')),
                ('total_disk', models.FloatField(blank=True, null=True, verbose_name='Total Disk (GB)')),
                ('free_disk', models.FloatField(blank=True, null=True, verbose_name='Free Disk (GB)')),
                ('cpu_cores', models.IntegerField(blank=True, null=True, verbose_name='CPU Cores')),
                ('load_average', models.FloatField(blank=True, null=True, verbose_name='Load Average')),
                ('labels', models.JSONField(blank=True, default=list, verbose_name='Labels')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synced At')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='jenkins_app.jenkinsserver')),
            ],
            options={
                'db_table': 'jenkins_nodes',
                'ordering': ['server', 'name'],
            },
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jenkins_app.jenkinsserver'),
        ),
        migrations.CreateModel(
            name='JenkinsCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_id', models.CharField(max_length=200, verbose_name='Credential ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('credential_type', models.CharField(choices=[('username_password', 'Username/Password'), ('ssh_key', 'SSH Key'), ('secret_text', 'Secret Text'), ('secret_file', 'Secret File'), ('certificate', 'Certificate')], max_length=50, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=500, verbose_name='Password')),
                ('private_key', models.TextField(blank=True, verbose_name='Private Key')),
                ('passphrase', models.CharField(blank=True, max_length=500, verbose_name='Passphrase')),
                ('secret', models.CharField(blank=True, max_length=2000, verbose_name='Secret')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('system', 'System')], default='global', max_length=50, verbose_name='Scope')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synced At')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='jenkins_app.jenkinsserver')),
            ],
            options={
                'db_table': 'jenkins_credentials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JenkinsView',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('view_id', models.CharField(max_length=200, verbose_name='View ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, verbose_name='View URL')),
                ('view_type', models.CharField(blank=True, max_length=50, verbose_name='Type')),
                ('jobs', models.JSONField(blank=True, default=list, help_text='List of job names in this view', verbose_name='Jobs')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='jenkins_app.jenkinsserver')),
            ],
            options={
                'db_table': 'jenkins_views',
                'ordering': ['server', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JenkinsBuild',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('build_number', models.IntegerField(verbose_name='Build Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('aborted', 'Aborted'), ('unstable', 'Unstable'), ('not_built', 'Not Built')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Duration (s)')),
                ('estimated_duration', models.FloatField(blank=True, null=True, verbose_name='Estimated Duration (s)')),
                ('result', models.CharField(blank=True, max_length=50, verbose_name='Result')),
                ('url', models.URLField(blank=True, verbose_name='Build URL')),
                ('console_output', models.TextField(blank=True, verbose_name='Console Output')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parameters')),
                ('causes', models.JSONField(blank=True, default=list, verbose_name='Causes')),
                ('built_by', models.CharField(blank=True, max_length=200, verbose_name='Built By')),
                ('test_results', models.JSONField(blank=True, default=dict, verbose_name='Test Results')),
                ('artifacts', models.JSONField(blank=True, default=list, verbose_name='Artifacts')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='Metrics')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_builds', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='jenkins_app.jenkinsjob')),
            ],
            options={
                'db_table': 'jenkins_builds',
                'ordering': ['-build_number'],
                'indexes': [models.Index(fields=['job', '-build_number'], name='jenkins_bui_job_id_b4dbba_idx'), models.Index(fields=['status'], name='jenkins_bui_status_7981ea_idx')],
                'unique_together': {('job', 'build_number')},
            },
        ),
        migrations.AddIndex(
            model_name='jenkinsserver',
            index=models.Index(fields=['name'], name='jenkins_ser_name_2ed424_idx'),
        ),
        migrations.AddIndex(
            model_name='jenkinsserver',
            index=models.Index(fields=['status'], name='jenkins_ser_status_ed0981_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jenkinsplugin',
            unique_together={('server', 'plugin_id')},
        ),
        migrations.AlterUniqueTogether(
            name='jenkinsnode',
            unique_together={('server', 'node_id')},
        ),
        migrations.AddIndex(
            model_name='jenkinsjob',
            index=models.Index(fields=['server', 'job_id'], name='jenkins_job_server__bc29bb_idx'),
        ),
        migrations.AddIndex(
            model_name='jenkinsjob',
            index=models.Index(fields=['job_type'], name='jenkins_job_job_typ_9b9781_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jenkinsjob',
            unique_together={('server', 'job_id')},
        ),
        migrations.AlterUniqueTogether(
            name='jenkinscredential',
            unique_together={('server', 'credential_id')},
        ),
        migrations.AlterUniqueTogether(
            name='jenkinsview',
            unique_together={('server', 'view_id')},
        ),
    ]
