# Generated by Django 6.0.3 on 2026-03-16 13:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EVENLab',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lab_path', models.CharField(help_text='Path in EVE-NG', max_length=500, verbose_name='Lab Path')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('lab_id', models.CharField(blank=True, max_length=100, verbose_name='Lab ID')),
                ('filename', models.CharField(blank=True, max_length=200, verbose_name='Filename')),
                ('folder', models.CharField(blank=True, max_length=500, verbose_name='Folder')),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('building', 'Building'), ('error', 'Error')], default='stopped', max_length=20, verbose_name='Status')),
                ('node_count', models.IntegerField(default=0, verbose_name='Node Count')),
                ('link_count', models.IntegerField(default=0, verbose_name='Link Count')),
                ('network_count', models.IntegerField(default=0, verbose_name='Network Count')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('topology', models.JSONField(blank=True, default=dict, verbose_name='Topology')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synced At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eveng_labs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eveng_labs',
                'ordering': ['server', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EVENNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.IntegerField(verbose_name='Node ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('node_type', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('host', 'Host'), ('server', 'Server'), ('vm', 'Virtual Machine'), ('docker', 'Docker Container'), ('other', 'Other')], default='other', max_length=50, verbose_name='Type')),
                ('image', models.CharField(blank=True, max_length=200, verbose_name='Image')),
                ('template', models.CharField(blank=True, max_length=200, verbose_name='Template')),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('building', 'Building'), ('error', 'Error'), ('unknown', 'Unknown')], default='stopped', max_length=20, verbose_name='Status')),
                ('cpu', models.IntegerField(default=1, verbose_name='CPU Cores')),
                ('ram', models.IntegerField(default=512, verbose_name='RAM (MB)')),
                ('ethernet', models.IntegerField(default=4, verbose_name='Ethernet Ports')),
                ('console', models.CharField(blank=True, max_length=50, verbose_name='Console')),
                ('console_type', models.CharField(choices=[('telnet', 'Telnet'), ('vnc', 'VNC'), ('spice', 'SPICE'), ('rdp', 'RDP')], default='telnet', max_length=20, verbose_name='Console Type')),
                ('console_port', models.IntegerField(blank=True, null=True, verbose_name='Console Port')),
                ('position_x', models.IntegerField(default=0, verbose_name='Position X')),
                ('position_y', models.IntegerField(default=0, verbose_name='Position Y')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('interfaces', models.JSONField(blank=True, default=list, verbose_name='Interfaces')),
                ('url', models.URLField(blank=True, verbose_name='Node URL')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='eveng_app.evenlab')),
            ],
            options={
                'db_table': 'eveng_nodes',
                'ordering': ['lab', 'node_id'],
            },
        ),
        migrations.CreateModel(
            name='EVENLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_label', models.CharField(blank=True, max_length=50, verbose_name='Source Label')),
                ('source_interface', models.CharField(blank=True, max_length=50, verbose_name='Source Interface')),
                ('destination_label', models.CharField(blank=True, max_length=50, verbose_name='Destination Label')),
                ('destination_interface', models.CharField(blank=True, max_length=50, verbose_name='Destination Interface')),
                ('link_type', models.CharField(choices=[('ethernet', 'Ethernet'), ('serial', 'Serial'), ('bridge', 'Bridge')], default='ethernet', max_length=50, verbose_name='Type')),
                ('color', models.CharField(default='#000000', max_length=50, verbose_name='Color')),
                ('width', models.IntegerField(default=2, verbose_name='Width')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='eveng_app.evenlab')),
                ('destination_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_links', to='eveng_app.evennode')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='eveng_app.evennode')),
            ],
            options={
                'db_table': 'eveng_links',
                'ordering': ['lab', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EVENServer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(help_text='e.g., http://eveng:80', verbose_name='EVE-NG URL')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=500, verbose_name='Password')),
                ('timeout', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)], verbose_name='Timeout (seconds)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20, verbose_name='Status')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='EVE-NG Version')),
                ('cpu_usage', models.FloatField(blank=True, null=True, verbose_name='CPU Usage %')),
                ('memory_usage', models.FloatField(blank=True, null=True, verbose_name='Memory Usage %')),
                ('disk_usage', models.FloatField(blank=True, null=True, verbose_name='Disk Usage %')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eveng_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eveng_servers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='evenlab',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='eveng_app.evenserver'),
        ),
        migrations.CreateModel(
            name='EVENImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('image_type', models.CharField(choices=[('qemu', 'QEMU'), ('iol', 'IOL'), ('dynamips', 'Dynamips'), ('docker', 'Docker')], max_length=50, verbose_name='Type')),
                ('path', models.CharField(max_length=500, verbose_name='Path')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Version')),
                ('size_mb', models.IntegerField(default=0, verbose_name='Size (MB)')),
                ('default_cpu', models.IntegerField(default=1, verbose_name='Default CPU')),
                ('default_ram', models.IntegerField(default=512, verbose_name='Default RAM (MB)')),
                ('default_ethernet', models.IntegerField(default=4, verbose_name='Default Ethernet')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synced At')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='eveng_app.evenserver')),
            ],
            options={
                'db_table': 'eveng_images',
                'ordering': ['server', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EVENUserSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=200, unique=True, verbose_name='Session ID')),
                ('cookie', models.TextField(blank=True, verbose_name='Cookie')),
                ('logged_in_at', models.DateTimeField(auto_now_add=True, verbose_name='Logged In At')),
                ('last_activity_at', models.DateTimeField(auto_now=True, verbose_name='Last Activity At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='eveng_app.evenserver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eveng_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eveng_user_sessions',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='EVENNetwork',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('network_id', models.IntegerField(verbose_name='Network ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('network_type', models.CharField(choices=[('bridge', 'Bridge'), ('nat', 'NAT'), ('host_only', 'Host Only'), ('cloud', 'Cloud')], default='bridge', max_length=50, verbose_name='Type')),
                ('left', models.IntegerField(default=0, verbose_name='Left')),
                ('top', models.IntegerField(default=0, verbose_name='Top')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='eveng_app.evenlab')),
            ],
            options={
                'db_table': 'eveng_networks',
                'ordering': ['lab', 'network_id'],
                'unique_together': {('lab', 'network_id')},
            },
        ),
        migrations.AddIndex(
            model_name='evennode',
            index=models.Index(fields=['lab', 'status'], name='eveng_nodes_lab_id_a83eee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evennode',
            unique_together={('lab', 'node_id')},
        ),
        migrations.AddIndex(
            model_name='evenlink',
            index=models.Index(fields=['lab', 'source_node', 'destination_node'], name='eveng_links_lab_id_5faa7a_idx'),
        ),
        migrations.AddIndex(
            model_name='evenserver',
            index=models.Index(fields=['name'], name='eveng_serve_name_472d18_idx'),
        ),
        migrations.AddIndex(
            model_name='evenserver',
            index=models.Index(fields=['status'], name='eveng_serve_status_c82c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='evenlab',
            index=models.Index(fields=['server', 'lab_path'], name='eveng_labs_server__4dd458_idx'),
        ),
        migrations.AddIndex(
            model_name='evenlab',
            index=models.Index(fields=['status'], name='eveng_labs_status_40d955_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evenlab',
            unique_together={('server', 'lab_path')},
        ),
        migrations.AlterUniqueTogether(
            name='evenimage',
            unique_together={('server', 'path')},
        ),
        migrations.AddIndex(
            model_name='evenusersession',
            index=models.Index(fields=['user', 'is_active'], name='eveng_user__user_id_085ed3_idx'),
        ),
    ]
