# Generated by Django 6.0.3 on 2026-03-16 15:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricCollection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metric_type', models.CharField(choices=[('ansible', 'Ansible'), ('terraform', 'Terraform'), ('jenkins', 'Jenkins'), ('grafana', 'Grafana'), ('eveng', 'EVE-NG'), ('users', 'Users'), ('system', 'System')], max_length=50, verbose_name='Metric Type')),
                ('metric_names', models.JSONField(blank=True, default=list, verbose_name='Metric Names')),
                ('retention_days', models.IntegerField(default=30, verbose_name='Retention Days')),
                ('aggregation', models.CharField(choices=[('avg', 'Average'), ('min', 'Minimum'), ('max', 'Maximum'), ('sum', 'Sum')], default='avg', max_length=20, verbose_name='Aggregation')),
            ],
            options={
                'db_table': 'monitoring_metric_collections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('webhook', 'Webhook'), ('telegram', 'Telegram')], max_length=50, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'db_table': 'monitoring_notification_channels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=20, verbose_name='Severity')),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('expired', 'Expired')], default='active', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('system', 'System'), ('device', 'Device'), ('interface', 'Interface'), ('application', 'Application'), ('custom', 'Custom')], default='system', max_length=20, verbose_name='Source')),
                ('metric_name', models.CharField(blank=True, max_length=200, verbose_name='Metric Name')),
                ('metric_value', models.FloatField(blank=True, null=True, verbose_name='Metric Value')),
                ('threshold_value', models.FloatField(blank=True, null=True, verbose_name='Threshold Value')),
                ('operator', models.CharField(blank=True, choices=[('>', '>'), ('<', '<'), ('>=', '>='), ('<=', '<='), ('==', '==')], max_length=10, verbose_name='Operator')),
                ('first_occurrence', models.DateTimeField(auto_now_add=True, verbose_name='First Occurrence')),
                ('last_occurrence', models.DateTimeField(auto_now=True, verbose_name='Last Occurrence')),
                ('occurrence_count', models.IntegerField(default=1, verbose_name='Occurrence Count')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('notifications_sent', models.IntegerField(default=0, verbose_name='Notifications Sent')),
                ('last_notification_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Notification At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.device')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.interface')),
            ],
            options={
                'db_table': 'monitoring_alerts',
                'ordering': ['-last_occurrence'],
            },
        ),
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('threshold_type', models.CharField(choices=[('system_cpu', 'System CPU Usage'), ('system_memory', 'System Memory Usage'), ('system_disk', 'System Disk Usage'), ('device_cpu', 'Device CPU Usage'), ('device_memory', 'Device Memory Usage'), ('device_temperature', 'Device Temperature'), ('device_reachability', 'Device Reachability'), ('interface_status', 'Interface Status'), ('interface_errors', 'Interface Errors'), ('interface_bandwidth', 'Interface Bandwidth'), ('application', 'Application Metric')], max_length=50, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('warning_threshold', models.FloatField(blank=True, null=True, verbose_name='Warning Threshold')),
                ('critical_threshold', models.FloatField(blank=True, null=True, verbose_name='Critical Threshold')),
                ('operator', models.CharField(choices=[('>', '>'), ('<', '<'), ('>=', '>='), ('<=', '<=')], default='>', max_length=10, verbose_name='Operator')),
                ('duration', models.IntegerField(default=0, help_text='Duration threshold must be exceeded before alert', verbose_name='Duration (seconds)')),
                ('silence_period', models.IntegerField(default=5, help_text='Minimum time between alerts', verbose_name='Silence Period (minutes)')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_thresholds', to=settings.AUTH_USER_MODEL)),
                ('devices', models.ManyToManyField(blank=True, help_text='Specific devices to monitor (leave empty for all)', related_name='alert_thresholds', to='inventory.device')),
            ],
            options={
                'db_table': 'monitoring_alert_thresholds',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('ansible', 'Ansible'), ('terraform', 'Terraform'), ('jenkins', 'Jenkins'), ('grafana', 'Grafana'), ('eveng', 'EVE-NG'), ('users', 'Users'), ('system', 'System')], db_index=True, max_length=50, verbose_name='Metric Type')),
                ('metric_name', models.CharField(max_length=200, verbose_name='Metric Name')),
                ('metric_value', models.FloatField(verbose_name='Metric Value')),
                ('tags', models.JSONField(blank=True, default=dict, verbose_name='Tags')),
                ('collected_at', models.DateTimeField(db_index=True, verbose_name='Collected At')),
            ],
            options={
                'db_table': 'monitoring_application_metrics',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['metric_type', '-collected_at'], name='monitoring__metric__5080be_idx'), models.Index(fields=['-collected_at'], name='monitoring__collect_63f3d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('widgets', models.JSONField(blank=True, default=list, verbose_name='Widgets')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitoring_dashboards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpu_usage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='CPU Usage %')),
                ('memory_usage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Memory Usage %')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature °C')),
                ('uptime', models.BigIntegerField(blank=True, null=True, verbose_name='Uptime (seconds)')),
                ('is_reachable', models.BooleanField(default=False, verbose_name='Is Reachable')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='Response Time (ms)')),
                ('collected_at', models.DateTimeField(db_index=True, verbose_name='Collected At')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='inventory.device')),
            ],
            options={
                'db_table': 'monitoring_device_metrics',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='InterfaceMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='Status')),
                ('rx_bytes', models.BigIntegerField(default=0, verbose_name='RX Bytes')),
                ('tx_bytes', models.BigIntegerField(default=0, verbose_name='TX Bytes')),
                ('rx_packets', models.BigIntegerField(default=0, verbose_name='RX Packets')),
                ('tx_packets', models.BigIntegerField(default=0, verbose_name='TX Packets')),
                ('rx_errors', models.BigIntegerField(default=0, verbose_name='RX Errors')),
                ('tx_errors', models.BigIntegerField(default=0, verbose_name='TX Errors')),
                ('rx_drops', models.BigIntegerField(default=0, verbose_name='RX Drops')),
                ('tx_drops', models.BigIntegerField(default=0, verbose_name='TX Drops')),
                ('rx_rate_bps', models.FloatField(blank=True, null=True, verbose_name='RX Rate (bps)')),
                ('tx_rate_bps', models.FloatField(blank=True, null=True, verbose_name='TX Rate (bps)')),
                ('collected_at', models.DateTimeField(db_index=True, verbose_name='Collected At')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='inventory.interface')),
            ],
            options={
                'db_table': 'monitoring_interface_metrics',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='sent', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='monitoring.alert')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitoring.notificationchannel')),
            ],
            options={
                'db_table': 'monitoring_notification_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpu_usage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='CPU Usage %')),
                ('cpu_count', models.IntegerField(default=0, verbose_name='CPU Count')),
                ('load_avg_1min', models.FloatField(blank=True, null=True, verbose_name='Load Average 1min')),
                ('load_avg_5min', models.FloatField(blank=True, null=True, verbose_name='Load Average 5min')),
                ('load_avg_15min', models.FloatField(blank=True, null=True, verbose_name='Load Average 15min')),
                ('memory_total', models.BigIntegerField(verbose_name='Memory Total (bytes)')),
                ('memory_available', models.BigIntegerField(verbose_name='Memory Available (bytes)')),
                ('memory_used', models.BigIntegerField(verbose_name='Memory Used (bytes)')),
                ('memory_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Memory Usage %')),
                ('disk_total', models.BigIntegerField(verbose_name='Disk Total (bytes)')),
                ('disk_used', models.BigIntegerField(verbose_name='Disk Used (bytes)')),
                ('disk_free', models.BigIntegerField(verbose_name='Disk Free (bytes)')),
                ('disk_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disk Usage %')),
                ('network_bytes_sent', models.BigIntegerField(verbose_name='Network Bytes Sent')),
                ('network_bytes_recv', models.BigIntegerField(verbose_name='Network Bytes Received')),
                ('network_packets_sent', models.BigIntegerField(verbose_name='Network Packets Sent')),
                ('network_packets_recv', models.BigIntegerField(verbose_name='Network Packets Received')),
                ('collected_at', models.DateTimeField(db_index=True, verbose_name='Collected At')),
            ],
            options={
                'db_table': 'monitoring_system_metrics',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['-collected_at'], name='monitoring__collect_d4bf0c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'severity'], name='monitoring__status_06318a_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['source'], name='monitoring__source_97e8c9_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['device'], name='monitoring__device__316a96_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-last_occurrence'], name='monitoring__last_oc_416e28_idx'),
        ),
        migrations.AddIndex(
            model_name='alertthreshold',
            index=models.Index(fields=['threshold_type', 'is_enabled'], name='monitoring__thresho_4b77f9_idx'),
        ),
        migrations.AddIndex(
            model_name='devicemetric',
            index=models.Index(fields=['device', '-collected_at'], name='monitoring__device__138cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='devicemetric',
            index=models.Index(fields=['-collected_at'], name='monitoring__collect_019609_idx'),
        ),
        migrations.AddIndex(
            model_name='interfacemetric',
            index=models.Index(fields=['interface', '-collected_at'], name='monitoring__interfa_2d6cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='interfacemetric',
            index=models.Index(fields=['-collected_at'], name='monitoring__collect_e79396_idx'),
        ),
    ]
