global:
  scrape_interval: 5s

scrape_configs:

  # =========================
  # Django App
  # =========================
  - job_name: 'django'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.177.136:8000']

  # =========================
  # Jenkins Metrics
  # =========================
  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['192.168.177.136:8080']

  # =========================
  # Prometheus itself
  # =========================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.177.136:9095']

  # =========================
  # Node Exporter (system metrics)
  # =========================
  - job_name: 'node'
    static_configs:
      - targets: ['192.168.177.136:9100']