# Generated by Django 6.0.3 on 2026-03-16 12:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrafanaServer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(help_text='e.g., http://grafana:3000', verbose_name='Grafana URL')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API Key')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=500, verbose_name='Password')),
                ('timeout', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)], verbose_name='Timeout (seconds)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20, verbose_name='Status')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Grafana Version')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grafana_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grafana_servers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrafanaOrganization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.IntegerField(verbose_name='Organization ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('address', models.JSONField(blank=True, default=dict, verbose_name='Address')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synced At')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='grafana_app.grafanaserver')),
            ],
            options={
                'db_table': 'grafana_organizations',
                'ordering': ['server', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GrafanaFolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder_uid', models.CharField(max_length=200, verbose_name='Folder UID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('url', models.URLField(blank=True, verbose_name='Folder URL')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synced At')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='grafana_app.grafanaserver')),
            ],
            options={
                'db_table': 'grafana_folders',
                'ordering': ['server', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GrafanaDatasource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datasource_uid', models.CharField(db_index=True, max_length=200, verbose_name='Datasource UID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('type', models.CharField(choices=[('prometheus', 'Prometheus'), ('graphite', 'Graphite'), ('influxdb', 'InfluxDB'), ('elasticsearch', 'Elasticsearch'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('cloudwatch', 'CloudWatch'), ('azure', 'Azure Monitor'), ('stackdriver', 'Google Stackdriver'), ('loki', 'Loki'), ('tempo', 'Tempo'), ('jaeger', 'Jaeger'), ('other', 'Other')], max_length=50, verbose_name='Type')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('access', models.CharField(choices=[('direct', 'Direct'), ('proxy', 'Proxy')], default='proxy', max_length=50, verbose_name='Access')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('basic_auth', models.BooleanField(default=False, verbose_name='Basic Auth')),
                ('basic_auth_user', models.CharField(blank=True, max_length=200, verbose_name='Basic Auth User')),
                ('basic_auth_password', models.CharField(blank=True, max_length=500, verbose_name='Basic Auth Password')),
                ('with_credentials', models.BooleanField(default=False, verbose_name='With Credentials')),
                ('json_data', models.JSONField(blank=True, default=dict, verbose_name='JSON Data')),
                ('secure_json_data', models.JSONField(blank=True, default=dict, verbose_name='Secure JSON Data')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('read_only', models.BooleanField(default=False, verbose_name='Read Only')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synced At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasources', to='grafana_app.grafanaserver')),
            ],
            options={
                'db_table': 'grafana_datasources',
                'ordering': ['server', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GrafanaDashboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dashboard_uid', models.CharField(db_index=True, max_length=200, verbose_name='Dashboard UID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('dashboard_json', models.JSONField(blank=True, default=dict, verbose_name='Dashboard JSON')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('url', models.URLField(blank=True, verbose_name='Dashboard URL')),
                ('slug', models.CharField(blank=True, max_length=200, verbose_name='Slug')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synced At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grafana_dashboards', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='grafana_app.grafanaserver')),
            ],
            options={
                'db_table': 'grafana_dashboards',
                'ordering': ['server', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GrafanaAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_id', models.IntegerField(db_index=True, verbose_name='Alert ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('firing', 'Firing'), ('resolved', 'Resolved'), ('paused', 'Paused'), ('unknown', 'Unknown')], default='pending', max_length=20, verbose_name='State')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=20, verbose_name='Severity')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('new_state_date', models.DateTimeField(blank=True, null=True, verbose_name='New State Date')),
                ('eval_data', models.JSONField(blank=True, default=dict, verbose_name='Evaluation Data')),
                ('execution_error', models.TextField(blank=True, verbose_name='Execution Error')),
                ('url', models.URLField(blank=True, verbose_name='Alert URL')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synced At')),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='grafana_app.grafanadashboard')),
                ('datasource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='grafana_app.grafanadatasource')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='grafana_app.grafanaserver')),
            ],
            options={
                'db_table': 'grafana_alerts',
                'ordering': ['-new_state_date'],
            },
        ),
        migrations.CreateModel(
            name='GrafanaSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_key', models.CharField(max_length=200, unique=True, verbose_name='Snapshot Key')),
                ('snapshot_url', models.URLField(verbose_name='Snapshot URL')),
                ('snapshot_json', models.JSONField(blank=True, default=dict, verbose_name='Snapshot JSON')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('created_by', models.CharField(blank=True, max_length=200, verbose_name='Created By')),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='grafana_app.grafanadashboard')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='grafana_app.grafanaserver')),
            ],
            options={
                'db_table': 'grafana_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrafanaTeam',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_id', models.IntegerField(verbose_name='Team ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('member_count', models.IntegerField(default=0, verbose_name='Member Count')),
                ('permission', models.IntegerField(default=0, verbose_name='Permission')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synced At')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='grafana_app.grafanaorganization')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='grafana_app.grafanaserver')),
            ],
            options={
                'db_table': 'grafana_teams',
                'ordering': ['server', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GrafanaUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='User ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('login', models.CharField(max_length=200, verbose_name='Login')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Editor', 'Editor'), ('Viewer', 'Viewer')], default='Viewer', max_length=50, verbose_name='Role')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Disabled')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('avatar_url', models.URLField(blank=True, verbose_name='Avatar URL')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Seen')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synced At')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='grafana_app.grafanaorganization')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='grafana_app.grafanaserver')),
            ],
            options={
                'db_table': 'grafana_users',
                'ordering': ['server', 'email'],
            },
        ),
        migrations.CreateModel(
            name='GrafanaPanel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('panel_id', models.IntegerField(verbose_name='Panel ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('panel_json', models.JSONField(blank=True, default=dict, verbose_name='Panel JSON')),
                ('grid_pos', models.JSONField(blank=True, default=dict, verbose_name='Grid Position')),
                ('targets', models.JSONField(blank=True, default=list, verbose_name='Targets')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='grafana_app.grafanadashboard')),
            ],
            options={
                'db_table': 'grafana_panels',
                'ordering': ['dashboard', 'panel_id'],
                'unique_together': {('dashboard', 'panel_id')},
            },
        ),
        migrations.AddIndex(
            model_name='grafanaserver',
            index=models.Index(fields=['name'], name='grafana_ser_name_18bc32_idx'),
        ),
        migrations.AddIndex(
            model_name='grafanaserver',
            index=models.Index(fields=['status'], name='grafana_ser_status_187bc7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grafanaorganization',
            unique_together={('server', 'org_id')},
        ),
        migrations.AlterUniqueTogether(
            name='grafanafolder',
            unique_together={('server', 'folder_uid')},
        ),
        migrations.AddIndex(
            model_name='grafanadatasource',
            index=models.Index(fields=['server', 'type'], name='grafana_dat_server__2d4680_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grafanadatasource',
            unique_together={('server', 'datasource_uid')},
        ),
        migrations.AddIndex(
            model_name='grafanadashboard',
            index=models.Index(fields=['server', 'dashboard_uid'], name='grafana_das_server__17a893_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grafanadashboard',
            unique_together={('server', 'dashboard_uid')},
        ),
        migrations.AddIndex(
            model_name='grafanaalert',
            index=models.Index(fields=['server', 'state'], name='grafana_ale_server__64c25c_idx'),
        ),
        migrations.AddIndex(
            model_name='grafanaalert',
            index=models.Index(fields=['severity'], name='grafana_ale_severit_e8e63e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grafanaalert',
            unique_together={('server', 'alert_id')},
        ),
        migrations.AlterUniqueTogether(
            name='grafanateam',
            unique_together={('server', 'team_id')},
        ),
        migrations.AddIndex(
            model_name='grafanauser',
            index=models.Index(fields=['server', 'email'], name='grafana_use_server__ad9678_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grafanauser',
            unique_together={('server', 'user_id')},
        ),
    ]
